"""made the dates optional

Revision ID: 1eaa5c1e6781
Revises: fd4332e283ce
Create Date: 2026-08-25 13:19:32.418518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eaa5c1e6781'
down_revision: Union[str, Sequence[str], None] = 'fd4332e283ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('albums', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('songs', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'release_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('albums', 'release_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
