"""Added Songs, Albums, Idols and Group tables

Revision ID: fd4332e283ce
Revises: 5b8d59f1a609
Create Date: 2026-08-25 13:16:48.464620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4332e283ce'
down_revision: Union[str, Sequence[str], None] = '5b8d59f1a609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_groups_slug'), 'groups', ['slug'], unique=True)
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_album_group_id', 'albums', ['group_id'], unique=False)
    op.create_index(op.f('ix_albums_slug'), 'albums', ['slug'], unique=True)
    op.create_table('idols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('korean_name', sa.String(), nullable=True),
    sa.Column('korean_stage_name', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_place', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('instagram_username', sa.String(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderchoice'), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_idol_country', 'idols', ['country'], unique=False)
    op.create_index('idx_idol_group_id', 'idols', ['group_id'], unique=False)
    op.create_index('idx_idol_stage_name', 'idols', ['stage_name'], unique=False)
    op.create_index(op.f('ix_idols_slug'), 'idols', ['slug'], unique=True)
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_song_album_id', 'songs', ['album_id'], unique=False)
    op.create_index('idx_song_title', 'songs', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_song_title', table_name='songs')
    op.drop_index('idx_song_album_id', table_name='songs')
    op.drop_table('songs')
    op.drop_index(op.f('ix_idols_slug'), table_name='idols')
    op.drop_index('idx_idol_stage_name', table_name='idols')
    op.drop_index('idx_idol_group_id', table_name='idols')
    op.drop_index('idx_idol_country', table_name='idols')
    op.drop_table('idols')
    op.drop_index(op.f('ix_albums_slug'), table_name='albums')
    op.drop_index('idx_album_group_id', table_name='albums')
    op.drop_table('albums')
    op.drop_index(op.f('ix_groups_slug'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
